model = "gpt-5.2-codex"
model_reasoning_effort="medium"
hide_agent_reasoning = true
network_access = true

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[features]
web_search_request = true
skills = true
rmcp_client = true

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--project", "$(pwd)"]
startup_timeout_sec = 60
[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"
[mcp_servers.chrome-devtools]
type = "stdio"
command = "npx"
args = ["chrome-devtools-mcp@latest"]
description = "Chrome DevTools MCP: run performance traces, inspect the DOM, and perform real-time debugging of your web pages â€” useful for browser automation, end-to-end testing, and capturing page artifacts."
[mcp_servers.shadcn]
command = "npx"
args = ["shadcn@latest", "mcp"]
description = "Shadcn UI MCP: specialized in generating components and UI patterns using the Shadcn UI library for React and Tailwind CSS."
[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_MCP_PAT_TOKEN"
startup_timeout_sec = 60
[mcp_servers.notion]
command = "npx"
args = ["-y", "mcp-remote", "https://mcp.notion.com/mcp"]
startup_timeout_sec = 60

[projects."/Users/piory/git/github.com/Piory/ghosgent"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/ROOT4-BEAUTY/r4-beauty"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/keita-keita-keita/mobic-buy"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/ROOT4-BEAUTY/alpha-server"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/Piory/dotfiles"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/keita-keita-keita/yuipoke"]
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true
