model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
project_doc_fallback_filenames = ["CLAUDE.md"]
hide_agent_reasoning = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]
personality = "pragmatic"

[features]
unified_exec = true
shell_snapshot = true
steer = true
collab = true
collaboration_modes = true
apps = true
personality = true

[mcp_servers.Serena]
command = "uvx"
args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "codex",
  "--project",
  "$(pwd)"
]
startup_timeout_sec = 60

[mcp_servers.Context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.Playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[mcp_servers.ChromeDevtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.GitHub]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "GITHUB_MCP_PAT_TOKEN"
startup_timeout_sec = 60

[projects."/Users/piory/git/github.com/Piory/ghosgent"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/ROOT4-BEAUTY/r4-beauty"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/keita-keita-keita/mobic-buy"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/ROOT4-BEAUTY/alpha-server"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/ROOT4-BEAUTY/alpha-client"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/Piory/dotfiles"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/keita-keita-keita/yuipoke"]
trust_level = "trusted"

[projects."/Users/piory/git/github.com/yu-dot-limited/mirai-teracy"]
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true

[tui]
status_line = [
  "codex-version",
  "model-with-reasoning",
  "context-used",
  "weekly-limit",
  "five-hour-limit"
]
